### ISSUE TITLE
OSX 10.10 Yosemite

### ISSUE THREAD

**Issue by stephanmg** [VRL-Studio/VRL-Studio#21]
Dear Michael,

somehow a student encountered the following problem in VRL-Studio on OSX 10.10 (Yosemite):

Control-Right-Click won't open the Component menu within VRL-Studio.
I'm not sure how this can happen (or how he reached this point).

```
VRL - Studio 0.4.5.7
(using VRL 0.4.3.0.2, build: 2015/11/05 13:13:30)
```

and

```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
```

I think wiping out the VRL-Studio directory ~/.vrl/ should resolve this issue.
Also, using the latest VRL-Studio version from the Website works (for me),
if I do a clean installation.

I'm not sure how this issue could evolve... as the initial installation worked.
Maybe this is of interest.

Best,
Stephan

**Comment by miho** [comment]
Strange. Thanks for reporting.

Some thoughts:

It looks like you are using the outdated Apple-Java which is from 2006. It's time to move on ;)

Actually, you should use the Java version that comes with VRL-Studio. This is automatically the case if you download VRL-Studio from the official webpage. Maybe you checked the Java-Version in the Terminal instead of VRL-Studio? The Java-Version installed on OS X is irrelevant for VRL-Studio since it is bundled with its own Java-Version. The output should look like this:

![image](https://cloud.githubusercontent.com/assets/225266/14366851/0ed0ff36-fd15-11e5-874e-0f33eb97f8ec.png)

Also make sure to open a project before trying to open the Canvas menu.

**Comment by stephanmg** [comment]
Oh @miho.
You're right, I checked in the terminal, sorry, not VRL-Studio.

I'll give this a shot and report the bundled Java version I use.

Best,
Stephan
