### ISSUE TITLE
Scale of components and fonts on 4K and higher resolutions

### ISSUE THREAD

**Issue by archenroot** [VRL-Studio/VRL-Studio#23]
The IDE on 4K screen can be read(I have good eyes so far), but I would prefer capability to scale the interface to be readable without issue on 4K and beyond monitors.

**Comment by miho** [comment]
I know this is a real issue on Windows and most Linux distros. On macOS, VRL-Studio scales nicely already, since the OS does solve the issue for us. I own a Surface Pro 4 and almost can't read the code editor anymore. I hear you. But unfortunately, only JDK9 will provide the necessary features. On JDK8 it is hard to achieve. 

There's a a workaround though:

Enable Windows to prioritise external manifests by creating and setting this registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\SideBySide\PreferExternalManifest (DWORD)` to `1`

Now add the manifest file listed below to the jre/$arch/bin folder:

**java.exe.manifest:**
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">

<description>eclipse</description>

<trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
  <security>
    <requestedPrivileges>
      <requestedExecutionLevel xmlns:ms_asmv3="urn:schemas-microsoft-com:asm.v3"
        level="asInvoker"
        ms_asmv3:uiAccess="false">
      </requestedExecutionLevel>
    </requestedPrivileges>
  </security>
</trustInfo>

<asmv3:application>
  <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
    <ms_windowsSettings:dpiAware xmlns:ms_windowsSettings="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</ms_windowsSettings:dpiAware>
  </asmv3:windowsSettings>
</asmv3:application>

</assembly>
```

**Comment by miho** [comment]
Finally, we fixed this issue for the windows build. You get a nicely scaled UI now! JDK9 improvements helped a lot here.

**Comment by archenroot** [comment]
I am actually on Gentoo Linux system(sorry not to mention this) on Qt5 (Kde plasma), but will test with JDK 9 to see any difference.
